# Generated by Django 4.2.3 on 2023-12-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
