# Generated by Django 4.2.3 on 2023-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_alter_todomodel_description_alter_todomodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
