# Generated by Django 4.2.3 on 2023-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_alter_todomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
