# Generated by Django 4.2.3 on 2024-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0005_alter_todomodel_id_alter_todomodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Incomplete'),
        ),
    ]
